import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

const manifest = require('../public/manifest.json')

export default function Home() {
  return (
    <>
      <Head>
        <title>Contracts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Contracts</h1>

        <pre>
{`Chain ID: ${manifest.deployments[0].chainId}
Deployer: ${manifest.deployments[0].deployer}`}
        </pre>
        <table>
          <thead>
            <tr>
              <th>Contract</th>
              <th>Address</th>
              <th>Version</th>
              <th>Last update</th>
              <th>From branch</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {Object.values(manifest.targets.user).map((target: any) => {
              const proxyName = `Proxy${target.target}`
              const proxy = manifest.targets.system[proxyName]
              const address = proxy.address

              function findDeployment(target: any) {
                for(let deployment of manifest.deployments) {
                  for(let event of deployment.events) {
                    if (event.type == 'deploy_impl' && event.target == target.target && event.version == target.version) {
                      return deployment
                    }   
                  }
                }
              }

              const deployment = findDeployment(target)
              const deploymentDate = (new Date(deployment.time)).toLocaleDateString()

              return (
                <tr key={address}>
                  <td>{target.target}</td>
                  <td>{address}</td>
                  <td>{target.version}</td>
                  <td>
                    <p>{deploymentDate}</p>
                  </td>
                  <td>
                    <p><b>{deployment.revision.branch}</b></p>
                    <p>
                      {deployment.revision.descriptor}
                    </p>
                  </td>
                  <td>
                    <Link href={`/contract/${target.target}/interact`}>Interact</Link>
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </main>
    </>
  )
}
