import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import { ethers } from 'ethers'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

const manifest = require('../../../public/manifest.json')

export default function Interact() {
    // Get id from URL
    const router = useRouter()
    const id = router.query.id as string
    // const id = router.query['id'] as string;
    // console.log(id)
    if(!id) return <></>

    return (
        <Body id={id} />
    )

}


const Body = ({ id }: any) => {
    // Find target.
    const proxyName = `Proxy${id}`
    const proxy = manifest.targets.system[proxyName]
    const address = proxy.address
    const impl = manifest.targets.user[id]
    const abi = impl.abi

    const provider = new ethers.JsonRpcProvider('http://localhost:8545')
    const signer = new ethers.Wallet('0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80', provider)
    const contract = new ethers.Contract(address, abi, signer)

    const [results, setResults] = useState({})

    const call = async (name: string, args: any) => {
        const tx = await contract[name](...args)
        const result = tx.hash ? tx.hash : tx
        setResults({ ...results, [name]: result })
    }

    return (
        <>
            <Head>
                <title>Interact</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>Interact: {id}</h1>

                <pre>
                    {`Chain ID: ${manifest.deployments[0].chainId}
Address: ${address}`}
                </pre>
                <table>
                    <thead>
                        <tr>
                            <th>Function</th>
                            <th>Arguments</th>
                            <th>Call</th>
                            <th>Results</th>
                        </tr>
                    </thead>
                    <tbody>
                        {abi.map((item: any) => {
                            if (item.type == 'function') {
                                return (
                                    <tr key={item.name}>
                                        <td>{item.name}</td>
                                        <td>
                                            {item.inputs.map((input: any) => {
                                                return (
                                                    <div key={input.name}>
                                                        <label htmlFor={input.name}>{input.name}</label><br/>
                                                        <input type="text" name={`${item.name}__${input.name}`} />
                                                    </div>
                                                )
                                            })}
                                        </td>
                                        <td>
                                            <button onClick={
                                                () => {
                                                    const args = item.inputs.map((input: any) => {
                                                        const inputElement = document.querySelector(`input[name=${item.name}__${input.name}]`) as HTMLInputElement
                                                        return inputElement.value
                                                    })
                                                    call(item.name, args)
                                                }
                                            }>Call</button>
                                        </td>
                                        <td>
                                            <pre>
                                                {/* @ts-ignore */}
                                                {`${(results[item.name]) || ''}`}
                                            </pre>
                                        </td>
                                    </tr>
                                )
                            }
                        })}
                    </tbody>
                </table>
            </main>
        </>
    )
}